version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-arithmetic-calculator-ui
    container_name: backend-arithmetic-calculator-ui
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
networks:
    app-network:
        driver: bridge
